export const RECHERCHER_ORGANISME_FORM_STATE = {
  INITIAL: "INITIAL",
  UAI_UNKNOWN: "UAI_UNKNOWN",
  UAI_NOT_FOUND: "UAI_NOT_FOUND",
  ONE_ORGANISME_FOUND: "ONE_ORGANISME_FOUND",
  MANY_ORGANISMES_FOUND: "MANY_ORGANISMES_FOUND",
  ERROR: "ERROR",
};

export const RECHERCHER_ORGANISME_SUBMIT_STATE = {
  WAITING: "WAITING",
  SUCCESS: "SUCCESS",
  FAIL: "FAIL",
};
